Actualize references
```
$ bundle exec rake references:verify
ERROR: https://twitter.com/schneems/status/1034123879978029057 (302)
ERROR: https://docs.gitlab.com/ee/development/performance.html#reading-from-files-and-other-data-sources (301)
```

Twitter 302 is due to domain change, but the tweat actually does not exist anymore
(see https://x.com/schneems/status/1034123879978029057)